markdown: kramdown
#permalink: /:title/
permalink: /:year/:month/:day/:title.html
url: https://Valdanitooooo.github.io
name: Valdanito
author: Valdanito
email: valdanito@qq.com
gitment: true
#weibo:
baidu-analysis: 591bc81097305e55717c37659435f4e9
github: Valdanitooooo
highlighter: rouge
gems: [jekyll-paginate]
safe: false
paginate: 10
paginate_path: '/index/page:num/'
#ipaginate: 20
port: 3999
