markdown: kramdown
permalink: /:title/
url: https://Valdanitooooo.github.io
name: Valdanito
author: Valdanito
email: valdanito@qq.com
duoshuo: Valdanito
weibo: 2075704727
github: Valdanitooooo
highlighter: rouge
safe: true
paginate: 20
