markdown: kramdown
permalink: /:title/
url: https://Valdanitooooo.github.io
name: Valdanito
author: Valdanito
email: valdanito@qq.com
gitment: true
weibo: 2075704727
github: Valdanitooooo
highlighter: rouge
safe: true
ipaginate: 20
port: 3999
